### ISSUE TITLE
broken "addons" link

### ISSUE THREAD

**Issue by loveshack** [OpenNebula/docs#853]
There are several broken links to http://opennebula.org/addons in the current version of the docs (master or 5.10).

**Comment by SuperKogito** [comment]
Broken links are a common issue and a radical solution to this problem is automatically checking and reporting them. Luckily the new GitHub actions and  workflows help with that. I recently wrote an action that just does that. [URLs-checker](https://github.com/marketplace/actions/urls-checker) will check and report broken links, which is useful to spot similar issues to this one.

**Comment by tinova** [comment]
@loveshack links should be changed in the repo right now, thanks for the heads up!

@SuperKogito that looks super useful. I've tried it out and the following issues prevent the usage of URLs-checker in our repo:

   - we need to whitelist some urls. For instance "https://x.x.x.x/mob/?moid=yyyyy" is an example URL and shouldn't give a warning (it would be nice to be able to curate a whitelist of URLs in the action conf file)
    - some urls (that are not valid, but should be whitelisted) breaks the action script

Feel free to take a look at: https://github.com/tinova/docs/runs/335326174

I'm happy to move this discussion to the URLs-checker repo if that's useful

**Comment by SuperKogito** [comment]
This is a great suggestion, it is actually on my agenda. I am just unsure if I should consider whitelisting a pattern or just a list of links. It will be better to move this discussion to the URLs-checker repo .

**Comment by tinova** [comment]
I've created a couple of issues to we can keep the discussion on the URLs-checker repo:

* https://github.com/SuperKogito/URLs-checker/issues/3
* https://github.com/SuperKogito/URLs-checker/issues/4
